# Generated by Django 4.2.9 on 2024-10-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearable',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='scenarioresult',
            name='ScenarioQuestion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.scenarioquestion'),
        ),
        migrations.AddField(
            model_name='scenarioresult',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='scenarioquestion',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='facesoul',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mentor_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.mentorprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userprofile'),
        ),
    ]
