# Generated by Django 4.2.9 on 2024-10-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioquestion',
            name='scenario3_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scenarioquestion',
            name='scenario3_image',
            field=models.ImageField(default='media/scenario/default.jpg', upload_to='media/scenario/'),
        ),
        migrations.AddField(
            model_name='scenarioquestion',
            name='scenario3_label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
