# Generated by Django 4.2.9 on 2024-10-08 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('otp_validity', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('resetToken', models.CharField(default='none', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('birthDate', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=18)),
                ('height', models.IntegerField(default=150)),
                ('weight', models.IntegerField(default=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('mentor_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=18)),
                ('birthDate', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('availibility', models.CharField(blank=True, default='Monday - Friday 10:00 AM - 6:00 PM', max_length=100, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('specialization', models.CharField(max_length=30)),
                ('serviceStatus', models.BooleanField(default=False)),
                ('mentor_queue_size', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
